name: SimpleLock
version: 1.0.2
main: me.fearlessstudios.simplelock.SimpleLockPlugin
api-version: '1.21'
author: FearlessStudios
softdepend: [Towny, Vault]

commands:
  simplelock:
    description: Main SimpleLock command
    usage: /simplelock <whitelist|transfer|settings|reload|updateconfig>
    aliases: [slock]

permissions:
  simplelock.admin:
    description: Bypass all protections
    default: op
  simplelock.settings:
    description: Open the SimpleLock settings GUI
    default: op
  simplelock.reload:
    description: Reload or update the SimpleLock config
    default: op
